#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Dgwt.args="-out www-test" -Xmx256M -cp "$APPDIR/src:$APPDIR/test:$APPDIR/bin:/Applications/eclipse/plugins/org.junit4_4.3.1/junit.jar:/Users/jesse/Desktop/stage/gwt-mac-1.5.3/gwt-user.jar:/Users/jesse/Desktop/stage/gwt-mac-1.5.3/gwt-dev-mac.jar" junit.textui.TestRunner com.hogbaysoftware.documents.client.DocumentsTest "$@";
